//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Storage pathes from user
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Storage pathes from user")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>one</string>\r\n  <string>two</string>\r\n  <string>tree</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection StoragePathesXml {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StoragePathesXml"]));
            }
            set {
                this["StoragePathesXml"] = value;
            }
        }
        
        /// <summary>
        /// Storage classes from storages scan
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Storage classes from storages scan")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>one</string>\r\n  <string>two</string>\r\n  <string>tree</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection StorageClassesXml {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StorageClassesXml"]));
            }
            set {
                this["StorageClassesXml"] = value;
            }
        }
        
        /// <summary>
        /// List of last used search patterns
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("List of last used search patterns")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>one</string>
  <string>two</string>
  <string>tree</string>
  <string>&lt;tree&gt;&amp;nbst;</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SearchPatternsXml {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchPatternsXml"]));
            }
            set {
                this["SearchPatternsXml"] = value;
            }
        }
        
        /// <summary>
        /// Search panel checkbox states
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Search panel checkbox states")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CheckBoxState {
            get {
                return ((int)(this["CheckBoxState"]));
            }
            set {
                this["CheckBoxState"] = value;
            }
        }
        
        /// <summary>
        /// RAM limit for search engine
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("RAM limit for search engine")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256000000")]
        public int MemoryLimit {
            get {
                return ((int)(this["MemoryLimit"]));
            }
            set {
                this["MemoryLimit"] = value;
            }
        }
    }
}
